title: Programación para Ciencia de Datos
author: Wilmer Pineda
logo: images/logo_sie.png  # si tienes uno
execute:
  execute_notebooks: auto
html:
  baseurl: https://pythoncienciadatossantoto.github.io/SIE_Convolutional_Neural_Networks/